spring:
  datasource:
    primary:
      url : jdbc:postgresql://localhost:5432/postgres
      username : XXXXX
      password : YYYYY
      driverClassName : org.postgresql.Driver
    secondary:
      url : jdbc:mysql://localhost:3306/blog?useSSL=false
      username : XXXXX
      password : YYYYY
      driverClassName : com.mysql.jdbc.Driver